boost_empty_carts: false
normal_cart_speed: 0.4
max_cart_speed: 1
slow_cart_speed: 0.1
pickup_radius: 3

# Don't touch this if you don't know what you're doing!
control_sign_prefix_regex: "^\\s*SC: "

elevator_block_material: "RED_WOOL"
intersection_block_material: "GREEN_WOOL"
kill_block_material: "YELLOW_WOOL"
slow_block_material: "ORANGE_WOOL"
spawn_block_material: "BLACK_WOOL"

# empty_cart_timer in seconds. set to 0 if you don't want to remove carts.
empty_cart_timer: 10
empty_cart_timer_ignore_storagemincart: true
empty_cart_timer_ignore_spawnermincart: true
empty_cart_timer_ignore_poweredmincart: true
empty_cart_timer_ignore_hoppermincart: true
empty_cart_timer_ignore_explosiveminecart: true
empty_cart_timer_ignore_commandminecart: true
