name: SmartCart
version: 1.0.1
description: A minecart transportation plugin!
authors: [floored1585, Seanboyy]
load: startup
main: SmartCart
api-version: 1.13
commands:
        sc:
                permission: op
                description: SmartCart Control
        scSetTag:
                permission: true
                description: SmartCart set cart tag