name: smartcart
version: 1.0.1
description: A minecart transportation plugin!
authors: [floored1585, Seanboyy]
load: STARTUP
main: io.github.seanboyy.smartcart.SmartCart
api-version: 1.13
commands:
        sc:
                permission: op
                description: smartcart Control
        scSetTag:
                description: smartcart set cart tag